# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      workflow-actions:
        patterns:
          - "*"
    allow:
      - dependency-name: "actions/*"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "7.2"
    schedule:
      interval: "weekly"
      day: "sunday"
    allow:
      - dependency-name: "org.hibernate.orm:*"
    ignore:
      - dependency-name: "org.hibernate.orm:*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "6.6"
    schedule:
      interval: "weekly"
      day: "sunday"
    allow:
      - dependency-name: "org.hibernate.orm:*"
    ignore:
      - dependency-name: "org.hibernate.orm:*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
